name: Data Collector Cron

on:
  schedule:
    - cron: "*/20 * * * *"   # cada 20 minutos
  workflow_dispatch:         # botón para ejecutarlo manual

jobs:
  run-datacollector:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          BRAWL_API_KEY: ${{ secrets.BRAWL_API_KEY }}
        run: |
          python datacollector.py